build_mac:
  script:
    - pwd
    - echo "SuCCeSS"
    - echo "after new key enabled"
    # - dir
    # - "################ NiftyMatch ################"
    # - cd ..
    # - rm -rf NiftyMatch-build NiftyMatch-install
    # - mkdir NiftyMatch-build NiftyMatch-install
    # - NiftyMatch_INSTALL_DIR=$(pwd)/NiftyMatch-install
    # - cd NiftyMatch-build
    # - cmake -DCMAKE_INSTALL_PREFIX="$NiftyMatch_INSTALL_DIR" ../NiftyMatch/src
    # - make -j
    # - make install
    # - ''
    # - "################ cuSIFT ################"
    # - cd ..
    # - rm -rf cuSIFT
    # - git clone git@cmiclab.cs.ucl.ac.uk:GIFT-Surg/cuSIFT.git cuSIFT --branch dev
    # - rm -rf cuSIFT-build
    # - mkdir cuSIFT-build
    # - cd cuSIFT-build
    # - cmake -DNiftyMatch_DIR="$NiftyMatch_INSTALL_DIR/include/nm" -DBUILD_TESTS=ON ../cuSIFT/src
    # - make -j
    # - ./cusift -s ../cuSIFT/data/placenta/source.jpg -t ../cuSIFT/data/placenta/target.jpg -o result.jpg
    # - make test
    # - ''
    # - "################ gpu-mosaicing ################"
    # - cd ..
    # - rm -rf gpu-mosaicing
    # - git clone git@cmiclab.cs.ucl.ac.uk:pdaga/gpu-mosaicing.git gpu-mosaicing --branch dev
    # - rm -rf gpu-mosaicing-build
    # - mkdir gpu-mosaicing-build
    # - cd gpu-mosaicing-build
    # - cmake -DQt5Widgets_DIR=/opt/QtSDK/5.5/gcc_64/lib/cmake/Qt5Widgets -DQt5OpenGL_DIR=/opt/QtSDK/5.5/gcc_64/lib/cmake/Qt5OpenGL -DUSE_LIBVLC=OFF -DNiftyMatch_DIR="$NiftyMatch_INSTALL_DIR/include/nm" ../gpu-mosaicing/src
    # - make -j
  tags:
    # - gift-linux
    # - cuda
    # - gift-adelie
    - gift-mac
    # - tmp-tag-for-testing
    # - tmp-tag-for-testing-cmiclab-lin
  # except:
  # - tags
