variables:
  - CI_SCRIPTS_DIR: "./ci"

before_script:
  - export SCRATCH_DIR="$(pwd)/../scratch-space"
  - export NiftyMatch_SOURCE_DIR="$(pwd)/src"
  - export NiftyMatch_BUILD_DIR="$SCRATCH_DIR/build/NiftyMatch"
  - export INSTALL_DIR="$SCRATCH_DIR/install"
  - export NiftyMatch_DIR="$INSTALL_DIR/include/nm"
  - export cuSIFT_REPO_DIR="$SCRATCH_DIR/source/cuSIFT"
  - export cuSIFT_SOURCE_DIR="$cuSIFT_REPO_DIR/src"
  - export cuSIFT_BUILD_DIR="$SCRATCH_DIR/build/cuSIFT"

# Linux ##################
gift-linux:
  script:
    - "$CI_SCRIPTS_DIR/build-linux.sh"
    - "$CI_SCRIPTS_DIR/deploy-linux.sh"
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-linux
    - cuda

# Mac ##################
gift-mac:
  script:
    - "$CI_SCRIPTS_DIR/build-mac.sh"
    - "$CI_SCRIPTS_DIR/deploy-mac.sh"
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-mac
    - cuda