before_script:
  - export SCRATCH_DIR=$(readlink -f "../scratch-space") # get absolute path
  - export NiftyMatch_SOURCE_DIR="$(pwd)/src"
  - export NiftyMatch_BUILD_DIR="$SCRATCH_DIR/build/NiftyMatch"
  - export INSTALL_DIR="$SCRATCH_DIR/install"
  - export NiftyMatch_DIR="$INSTALL_DIR/include/nm"
  - export cuSIFT_REPO_DIR="$SCRATCH_DIR/source/cuSIFT"
  - export cuSIFT_SOURCE_DIR="$cuSIFT_REPO_DIR/src"
  - export cuSIFT_BUILD_DIR="$SCRATCH_DIR/build/cuSIFT"

stages:
  - build
  - deploy # faking deploy for now, i.e. only for testing
  - test

build-linux:
  stage: build
  script: ./build.sh
  tags:
    - gift-linux
    - cuda

deploy-linux:
  stage: deploy
  script: ./deploy.sh
  tags:
    - gift-linux
    - cuda

test-linux:
  stage: test
  script: ./test.sh
  tags:
    - gift-linux
    - cuda